#!/usr/bin/env python3
"""Find registry items that have no recipe (never appear as an output).

Scans data/recipes/*.yaml for outputs/inputs/pattern cells, then reports
items from the registry that can never be crafted.

Categories reported:
  [needed]  no recipe, but used as an input somewhere  -> should get a recipe
  [dead]    no recipe, never mentioned anywhere        -> unreachable item
  [world]   no recipe, but name ends with _ore         -> generated by world, likely OK
  [reference] no recipe, only mentioned in patterns    -> used in crafting, should get a recipe

Exit code: 0 always (report-only). Use --fail-if-nonempty to fail when any
non-world item is missing a recipe (CI guard).
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")


def load_names(csv_path: Path) -> set[str]:
    """Load item names from a CSV: first line header, then `# comment` lines, then id,name,..."""
    names: set[str] = set()
    with open(csv_path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(",", 3)
            if len(parts) < 2:
                continue
            name = parts[1].strip()
            if not name or name.startswith("#"):
                continue
            # skip header row (e.g. "int,name,stack,meta")
            if parts[0].strip() in ("int", "id") and name == "name":
                continue
            names.add(name)
    return names


def load_markdown_names(md_path: Path) -> set[str]:
    """Extract item names from a markdown issue dump: only CSV-shaped lines (numeric id, name)."""
    names: set[str] = set()
    with open(md_path) as fh:
        for line in fh:
            line = line.strip()
            parts = line.split(",", 3)
            if len(parts) < 2:
                continue
            item_id, name = parts[0].strip(), parts[1].strip()
            if not re.fullmatch(r"[0-9:]+", item_id):
                continue  # prose line, not a registry row
            if not name or name.startswith("#"):
                continue
            names.add(name)
    return names


def cell_name(cell) -> str | None:
    """YAML pattern cells are plain strings; inputs/outputs items are `{item, count}` dicts."""
    if isinstance(cell, dict):
        v = cell.get("item")
        return str(v) if v else None
    if isinstance(cell, str):
        return cell
    return None


def scan_recipes(recipes_dir: Path) -> tuple[set[str], set[str], set[str]]:
    """Returns (produced, used_as_input, used_in_pattern)."""
    produced: set[str] = set()
    used_input: set[str] = set()
    used_pattern: set[str] = set()

    for yaml_file in sorted(recipes_dir.glob("*.yaml")):
        data = yaml.safe_load(open(yaml_file))
        for r in data.get("recipes", []):
            for o in r.get("outputs", []):
                n = cell_name(o)
                if n:
                    produced.add(n)
            for i in r.get("inputs", []):
                n = cell_name(i)
                if n:
                    used_input.add(n)
            for row in r.get("pattern", []):
                for cell in row:
                    n = cell_name(cell)
                    if n and n != "~":
                        used_pattern.add(n)
    return produced, used_input, used_pattern


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    root = Path(__file__).parent.parent
    ap.add_argument("--registry", type=Path, default=root / "data" / "registry" / "items.csv")
    ap.add_argument("--recipes-dir", type=Path, default=root / "data" / "recipes")
    ap.add_argument("--todo", type=Path, default=None, help="Extra CSV to include in the universe (e.g. todo_items/items (1).csv)")
    ap.add_argument("--issue-md", type=Path, action="append", default=[], help="Markdown issue dump with a registry CSV block (e.g. todo_items/issue21.md); repeatable")
    ap.add_argument("--fail-if-nonempty", action="store_true", help="Exit 1 if any non-world item lacks a recipe")
    args = ap.parse_args()

    universe = load_names(args.registry)
    extra = set()

    # Temporary registry additions (data/registry/items2.csv) are part of the universe.
    items2 = args.registry.parent / "items2.csv"
    if items2.exists():
        extra |= load_names(items2)

    if args.todo:
        extra |= load_names(args.todo)
    for md in args.issue_md:
        extra |= load_markdown_names(md)
    universe |= extra
    produced, used_input, used_pattern = scan_recipes(args.recipes_dir)

    def is_ore(name: str) -> bool:
        return "_ore" in name or name in ("raw_ore_block",) or name.endswith("_ore_block")

    no_recipe = universe - produced
    needed = sorted(n for n in no_recipe if n in used_input and not is_ore(n))
    world = sorted(n for n in no_recipe if is_ore(n))
    pattern_only = sorted(n for n in no_recipe if n in used_pattern and n not in used_input and not is_ore(n))
    dead = sorted(n for n in no_recipe if n not in used_input and n not in used_pattern and not is_ore(n))

    print(f"universe: {len(universe)} items ({len(extra)} from extra CSV)")
    print(f"recipes : {len(produced)} items craftable, {len(used_input)} used as input, {len(used_pattern)} in patterns")
    print(f"no recipe: {len(no_recipe)} items\n")

    def dump(title: str, items: list[str], hint: str):
        print(f"=== {title} ({len(items)}) {hint}")
        for n in items:
            extra_mark = " [todo]" if args.todo and n in extra else ""
            print(f"  {n}{extra_mark}")
        print()

    dump("NEEDED  — no recipe, used as input", needed, "<- craft these")
    dump("PATTERN — no recipe, only in patterns", pattern_only, "<- craft these too")
    dump("WORLD   — no recipe, ore-ish", world, "<- generated, usually fine")
    dump("DEAD    — no recipe, never used", dead, "<- unreachable or placeholder")

    non_world_missing = len(needed) + len(pattern_only) + len(dead)
    if args.fail_if_nonempty and non_world_missing > 0:
        sys.exit(f"{non_world_missing} non-world items have no recipe")
    sys.exit(0)


if __name__ == "__main__":
    main()